// Content marketing — real, substantive articles for organic search and the
// GTM playbook's "content loop" (see docs/05-business/gtm-strategy.md).
// Static data by design, same pattern as lib/verticals.ts: no CMS dependency,
// swap for a headless CMS query once there's an editorial team to run one.

export type ArticleBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'quote'; text: string }
  | { type: 'list'; items: string[] };

export interface Article {
  slug: string;
  title: string;
  dek: string;
  category: 'Ops' | 'Growth' | 'Product' | 'Privacy' | 'Playbook';
  readMinutes: number;
  publishedAt: string; // ISO date, no time — editorial date, not a timestamp
  body: ArticleBlock[];
  cta: { label: string; href: string };
  /** Smart cross-link into a /workshops/[type] page — set when the article's real
   *  example (clay, lumber, a kitchen) maps to a specific craft, for lead-gen. */
  relatedWorkshopType?: import('./workshop-types').WorkshopTypeId;
}

export const ARTICLES: Article[] = [
  {
    slug: 'seven-app-problem',
    title: 'The seven-app problem: why your club runs on duct tape',
    dek: 'WhatsApp for chatter, Strava for miles, Eventbrite for tickets, Sheets for members, Instagram for reach, PayPal for dues. Seven tools, zero of them talking to each other.',
    category: 'Ops',
    readMinutes: 5,
    publishedAt: '2026-05-04',
    body: [
      { type: 'p', text: 'Ask any organizer how their club actually runs and you get the same answer in a different order every time: a WhatsApp group for chatter, Strava for who ran what, Eventbrite for the race-day ticket, a Google Sheet for the member list, Instagram for reach, and PayPal or Venmo for dues. Seven tools. None of them know the other six exist.' },
      { type: 'p', text: "That gap gets bridged by a person, not software. Someone copies RSVP counts from Eventbrite into the Sheet. Someone screenshots the WhatsApp poll into a caption. Someone manually reconciles who paid dues against who showed up. That person is usually a volunteer with a full-time job elsewhere, and the club's entire operating capacity is bounded by how much of their evening they have left." },
      { type: 'h2', text: 'The tools are excellent. The seams are the problem.' },
      { type: 'p', text: "This isn't a knock on any one tool — Strava is genuinely the best place to log a run, and WhatsApp is genuinely the best place for a group chat. The failure mode is structural: each tool optimizes for its own slice and has no reason to talk to the others. Eventbrite doesn't know a member's attendance history. Strava doesn't know who owes dues. Nobody owns the connective layer, so a human has to be it." },
      { type: 'list', items: [
        'A new member has to be re-entered in the Sheet, added to WhatsApp, and told where to find the Strava club — three separate onboarding steps, one for each disconnected tool.',
        'Attendance lives in someone\'s head or a Sheet nobody else can find, so "who\'s at risk of drifting away" is a guess, not a report.',
        'Eventbrite\'s 5%+ ticket fee is a tax on the one part of the stack that touches money — paid by a nonprofit club, to a company that has no idea the club exists.',
      ] },
      { type: 'h2', text: 'What changes when it\'s one system' },
      { type: 'p', text: "The fix isn't a better spreadsheet template. It's collapsing the seams: one member record that events, payments, and communications all read from and write to. Publish an event once and the landing page, registration, reminders, and QR check-in all exist automatically, because they're views onto the same data — not five separate configurations a volunteer has to keep in sync by hand." },
      { type: 'quote', text: 'Strava owns activity. Eventbrite owns events. Nobody owns the operating system underneath a running club — that\'s the actual gap.' },
      { type: 'p', text: "You can see the smallest version of this collapse in under a minute: create a real event, get a real RSVP, no account required. It's the same engine that runs the full club workspace underneath, just with the training wheels of a login removed." },
    ],
    cta: { label: 'Create a real event in 60 seconds — no account →', href: '/new' },
  },
  {
    slug: 'qr-checkin-vs-clipboard',
    title: 'QR check-in vs. the clipboard: what actually changes on race morning',
    dek: 'A clipboard tells you who signed a piece of paper. A QR check-in tells you who\'s actually there, in real time, on every device your volunteers are holding.',
    category: 'Product',
    readMinutes: 4,
    publishedAt: '2026-05-18',
    body: [
      { type: 'p', text: "Every organizer has run the clipboard at least once: a printed roster, a pen tied to it with string, and a volunteer squinting to match a name against a list in the dark at 6:15am. It works, technically. It also doesn't scale past about thirty people before the line backs up and the pen goes missing." },
      { type: 'h2', text: 'The clipboard\'s real failure mode isn\'t the paper' },
      { type: 'p', text: "It's that the data dies the moment the event ends. Someone has to retype the roster into a spreadsheet afterward — or, more often, nobody does, and 'who actually showed up' becomes a question nobody can answer three weeks later when you're deciding who to invite back for a smaller, more committed group." },
      { type: 'list', items: [
        'QR check-in: scan → confirmed, instantly, on the same device every volunteer already has in their pocket.',
        'Idempotent by design — the same person scanning twice doesn\'t double-count, so nobody has to babysit the register.',
        'The count updates live for every volunteer at every entry point, not just the one holding the clipboard.',
        'Attendance becomes a permanent record automatically — no retyping, no "I\'ll do it later" that never happens.',
      ] },
      { type: 'h2', text: 'Why this matters more than it sounds like it should' },
      { type: 'p', text: "Attendance history is the input to almost everything else an organizer wants to do: knowing who's drifting away before they quit silently, knowing which members to ask for a testimonial, knowing whether a sponsor's activation actually reached people. A clipboard that gets thrown out after the event throws all of that away with it." },
      { type: 'p', text: 'This is one of the smaller surfaces in the product, and one of the easiest to underrate until you\'ve run a 200-person race morning with a spreadsheet instead. It\'s live in the full organizer workspace today — the demo walks through mission control, live arrival feed included.' },
    ],
    cta: { label: 'See the QR check-in mission control in the demo →', href: '/demo' },
  },
  {
    slug: 'real-cost-of-eventbrite-fees',
    title: 'The real cost of Eventbrite fees for community organizers',
    dek: 'A 5%+ ticket fee sounds small until you add up a season of races, workshops, and socials — and realize the fee doesn\'t shrink as the club grows. It grows with it.',
    category: 'Growth',
    readMinutes: 4,
    publishedAt: '2026-06-01',
    body: [
      { type: 'p', text: "Ticketing fees are usually framed as a rounding error: a few percent, easy to shrug off against the convenience of not building your own registration flow. But a running club or workshop studio isn't selling one ticket — it's selling hundreds across a season, and a flat percentage fee doesn't get cheaper as volume goes up. It gets bigger, in absolute terms, exactly when the club can least afford to keep paying a tax on its own growth." },
      { type: 'h2', text: 'Fees that grow against you vs. fees that shrink with you' },
      { type: 'p', text: 'The alternative worth asking for is a platform fee structure that moves the other direction: higher on a small club just getting started (when the absolute dollars are tiny anyway), and lower as the club scales past the point where a fixed percentage starts to really hurt. A fee that shrinks from 2% down to 0.5% as a club grows is a fundamentally different incentive than one that\'s flat no matter what.' },
      { type: 'list', items: [
        'Ticketing fees below the standard ~5%+, waived entirely on the higher tiers once a club is running at scale.',
        'A platform fee that moves 2% → 1% → 0.5% as membership grows — the platform makes money by the club growing, not by taxing every transaction at the same rate forever.',
        'No fee at all on the free tier: any one-off event under 20 people costs nothing, permanently, no trial period expiring.',
      ] },
      { type: 'h2', text: 'The honest version of this argument' },
      { type: 'p', text: "This only holds up if the alternative platform is actually solving a bigger problem than ticketing — otherwise it's just a different vendor taking a cut. The pitch here is that the same system handling the ticket also handles the member record, the reminders, the check-in, and the social promotion, so the fee is buying the collapse of six tools into one, not just a marginally cheaper checkout page." },
      { type: 'quote', text: 'Members never pay. The club subscribes, and the platform fee shrinks as the club grows — the incentive points the same direction as the organizer\'s.' },
    ],
    cta: { label: 'See the full pricing breakdown →', href: '/pricing' },
  },
  {
    slug: 'consent-not-compliance',
    title: 'Consent, not compliance: how member data should actually work',
    dek: 'GDPR compliance is a checkbox exercise if it stops at a cookie banner. The harder, more useful version gives every member real control over exactly what a club can see.',
    category: 'Privacy',
    readMinutes: 5,
    publishedAt: '2026-06-15',
    body: [
      { type: 'p', text: "Most consumer software treats privacy as a compliance cost: the minimum disclosure required to avoid a fine, buried in a settings page nobody visits. For a running club, that's the wrong frame entirely — the data in question is often genuinely sensitive (health metrics, location patterns, contact details for minors in youth programs) and it's being handled by a volunteer organizer, not a corporate data team with a legal department." },
      { type: 'h2', text: 'What "scoped consent" actually means in practice' },
      { type: 'p', text: 'Rather than one blanket privacy policy a member agrees to once and forgets, the right model is a small number of independently revocable scopes: does the club see your weekly mileage? Your PRs? Your contact email for sponsor offers? Each scope is a separate, visible toggle a member controls at any time — not a single all-or-nothing agreement.' },
      { type: 'list', items: [
        'Activity summary (weekly km, PRs) — off by default; a member opts in if they want the club to see their training trend.',
        'Contact sharing for sponsor perks — separate from event communications, so a discount code offer doesn\'t require handing over the same access as a race-day reminder.',
        'Health-scope data (if collected at all) never flows through the general API — it\'s architecturally separated, not just policy-separated.',
      ] },
      { type: 'h2', text: 'Why this is a moat, not just a compliance line item' },
      { type: 'p', text: "A club that can honestly tell members 'you control exactly what we see, scope by scope' earns a level of trust that a generic events platform never has a reason to build, because ticketing software doesn't need an ongoing relationship with the attendee. A community operating system does — and the consent model is what makes that relationship durable instead of extractive." },
      { type: 'p', text: "This is also, bluntly, a defensibility argument: a consented data layer that members actively trust is hard for a competitor to copy by just shipping a similar feature list, because trust is earned over time, not deployed in a sprint." },
    ],
    cta: { label: 'Read the permission model in the architecture docs →', href: '/pricing' },
  },
  {
    slug: 'whatsapp-group-to-workspace',
    title: 'From WhatsApp group to workspace: a migration playbook',
    dek: 'You don\'t need to migrate your whole club in one weekend. Here\'s the order that actually works, in five steps, none of which require your members to do anything.',
    category: 'Playbook',
    readMinutes: 6,
    publishedAt: '2026-06-22',
    body: [
      { type: 'p', text: "The instinct when adopting new club software is to try to move everything at once: import every member, recreate every past event, migrate the whole group chat history. That's exactly the amount of work that causes organizers to give up halfway through a Sunday afternoon and go back to the spreadsheet. The migration that actually sticks is smaller and sequenced." },
      { type: 'h2', text: 'Step 1 — publish one real event, change nothing else' },
      { type: 'p', text: "Before touching the member list or announcing anything, publish a single upcoming run, class, or workshop as a real event. This gets you a shareable public page, registration, and QR check-in for one session, with zero disruption to how the club currently communicates. If this step doesn't feel effortless, stop here — nothing downstream will feel effortless either." },
      { type: 'h2', text: 'Step 2 — import members without re-onboarding anyone' },
      { type: 'p', text: 'A CSV of names and emails (or a pasted list straight from the group chat) becomes the member list in under a minute — nobody has to create an account, set a password, or download anything. This is deliberately the lowest-friction step in the whole migration: the organizer does it once, alone, and nothing changes from the member\'s side yet.' },
      { type: 'h2', text: 'Step 3 — let the automations run on the next event, not a backlog' },
      { type: 'p', text: "Reminders, the social campaign draft, and check-in only need to work on the next event — there's no requirement to backfill history for events that already happened. Momentum comes from one good live example, not from perfectly reconstructing the past." },
      { type: 'h2', text: 'Step 4 — keep the WhatsApp group. Seriously.' },
      { type: 'list', items: [
        'The group chat stays exactly where it is — nothing here replaces the social layer members already like.',
        'What moves is the operational load: who\'s registered, who\'s paid, who checked in, what the reminder sequence says.',
        'Members experience one new thing at a time (a nicer event page, then a QR code, then a reminder) rather than a single jarring "we switched platforms" announcement.',
      ] },
      { type: 'h2', text: 'Step 5 — bring the volunteer who was the API into the loop last' },
      { type: 'p', text: 'The person manually reconciling spreadsheets and screenshots is usually the most skeptical of a new tool, reasonably so — they\'ve been burned by "this will save you time" promises before. Show them the reduced version of their own job after steps 1–4 are already live, rather than asking them to take that on faith up front.' },
      { type: 'quote', text: 'The founding-club program does this migration white-glove — but the same five steps work solo, in an afternoon, for any organizer willing to start with one event.' },
    ],
    cta: { label: 'Start the onboarding wizard →', href: '/start' },
  },
  {
    slug: 'what-a-digital-chief-of-staff-does',
    title: 'What a digital chief of staff actually does for a volunteer-run club',
    dek: 'Pacer doesn\'t replace the organizer. It does the unglamorous analysis work nobody has time for on top of a full-time job: predicting attendance, flagging churn, drafting the sponsor pitch.',
    category: 'Product',
    readMinutes: 5,
    publishedAt: '2026-06-29',
    body: [
      { type: 'p', text: 'Most "AI for X" pitches are vague on purpose, because a specific claim is easier to disprove. So here\'s a specific one: a club\'s digital chief of staff should be able to look at the member and event data a club already has, and answer three questions an organizer genuinely doesn\'t have time to work out by hand every week.' },
      { type: 'h2', text: 'Question 1 — who\'s about to churn, before they say anything' },
      { type: 'p', text: "A member who's gone from weekly to monthly to nothing over eight weeks rarely announces it. They just stop showing up, and by the time an organizer notices the gap in the attendance sheet, the member has usually already mentally left. Pacer's job is to surface that drift pattern early enough that a personal check-in message actually has a chance of working." },
      { type: 'h2', text: 'Question 2 — how many people will actually show up' },
      { type: 'p', text: "RSVP counts and actual attendance are different numbers, and the gap between them is exactly the information an organizer needs to plan capacity, order the right amount of water, or decide whether to open a waitlist. A prediction grounded in this club's own historical show-up rate — not an industry-wide average — is the useful version of this." },
      { type: 'h2', text: 'Question 3 — what does the sponsor pitch actually say' },
      { type: 'p', text: "Most volunteer organizers have never written a sponsorship proposal and don't have a template. Drafting one from the club's real, verified data — member count, weekly active rate, past event attendance — turns a blank page into a five-minute edit instead of a multi-hour research project the organizer keeps postponing." },
      { type: 'list', items: [
        'Attendance and churn predictions grounded in this club\'s own history, not generic benchmarks.',
        'Sponsor proposal drafts pulled from verified club data, not invented statistics.',
        'A full month planned out — event cadence, content calendar, and outreach — in one sitting instead of scattered across a week.',
      ] },
      { type: 'p', text: "None of this replaces the organizer's judgment about their own community — it replaces the hours of manual analysis that judgment currently has to compete with for time." },
    ],
    cta: { label: 'Ask Pacer a question in the live demo →', href: '/demo' },
  },
  {
    slug: 'pace-groups-without-whiteboard',
    title: "Pace groups without the whiteboard: sorting 60 runners who don't want to stand in a line",
    dek: "A folding whiteboard, three pace ranges in dry-erase marker, and sixty people squinting at handwriting from fifteen feet away. The sorting problem gets solved from scratch every single Saturday.",
    category: 'Ops',
    readMinutes: 5,
    publishedAt: '2026-01-08',
    body: [
      { type: 'p', text: "Every Saturday at 8:58 a.m., someone drags a folding whiteboard out of a car trunk and writes three pace ranges on it in dry-erase marker: 7:30s, 9:00s, 11:00-and-up. Sixty runners cluster around trying to read handwriting from fifteen feet away, guess which line applies to them, and reshuffle twice when the '9:00 group' turns out to have four genuinely different paces standing inside it. By the time everyone's sorted, the run that was supposed to start at 9:00 starts at 9:11." },
      { type: 'h2', text: 'The whiteboard works at fifteen people and breaks at forty' },
      { type: 'p', text: "At fifteen regulars, an organizer can eyeball the crowd and sort it correctly without a board at all — they know who runs what. At forty or sixty, that same organizer is sorting strangers and semi-strangers by self-report, and self-report skews in two directions: new or nervous runners guess slow to avoid embarrassment, first-timers guess fast out of optimism. Neither guess is the number that shows up on their watch a mile in." },
      { type: 'p', text: "The result is predictable and repeats weekly: watches chirp in unison at the start line, and within four hundred meters the 'group' has already split into three actual groups, because sorting by self-report and sorting by real pace are two different exercises wearing the same whiteboard." },
      { type: 'h2', text: "Nobody actually signed up to lead group C" },
      { type: 'p', text: "Once the three lines are drawn, someone still has to lead the middle one — and that's usually decided in the ninety seconds before the run starts, by whichever veteran member happens to be standing closest to that cluster, not by anyone who planned their Saturday around it." },
      { type: 'list', items: [
        'New or guest runners guessing their own pace, usually optimistically, which puts them in a group that drops them within the first mile.',
        'A veteran member volunteering to "just lead the middle group" on the spot, because someone has to, not because they planned for it.',
        'Watches chirping the start in unison, then the group splitting apart within four hundred meters once self-reported pace meets actual pace.',
        'Latecomers who missed the whiteboard sorting entirely and just pick whichever cluster of runners looks roughly their speed.',
      ] },
      { type: 'h2', text: 'What the event page could already know before anyone shows up' },
      { type: 'p', text: "A club that's been logging its runs has the one input the whiteboard doesn't: actual pace history per member, not a guess made under social pressure at 8:58 a.m. That data can pre-sort a Saturday event into suggested groups on the event page days in advance, with a leader assigned per group ahead of time — someone who opted in, not someone who got cornered at the line. Runners still adjust on arrival if they're feeling fast or slow, but they're starting from a real number instead of a guess written on a board." },
      { type: 'quote', text: "A whiteboard has to be re-solved every single week. A pace history doesn't." },
      { type: 'p', text: "None of this requires the club to become more formal — it just moves the sorting decision from Saturday morning, under time pressure, to sometime earlier in the week, when there's actually time to get it right." },
    ],
    cta: { label: 'Publish your next group run in 60 seconds →', href: '/new' },
  },
  {
    slug: 'volunteer-roster-race-day',
    title: 'The volunteer roster problem: race-day coverage without ten phone calls',
    dek: "Eighteen volunteers, six water stations, three marshal points. Two days out, the coordinator is re-asking the same question in three different group chats and still doesn't have a real headcount.",
    category: 'Ops',
    readMinutes: 4,
    publishedAt: '2026-01-15',
    body: [
      { type: 'p', text: "A club's biggest event of the year needs eighteen volunteers covering six water stations and three marshal points. Two days before race morning, the coordinator sends essentially the same message into three different group chats — the core team chat, the general club chat, and a direct text to the four people who bailed last year — asking who's still confirmed. Half don't answer until Saturday morning, if they answer at all." },
      { type: 'h2', text: "The group-chat scramble has a deadline it can't hit" },
      { type: 'p', text: "This isn't a communication failure so much as a format failure: a group chat is built for conversation, not for tracking coverage. There's no single view that says, as of right now, which of the nine posts are actually staffed — just a scroll of messages the coordinator has to mentally reconcile into a headcount, redone from scratch every time someone new replies or drops out." },
      { type: 'h2', text: 'No-shows get discovered at the worst possible moment' },
      { type: 'p', text: "Because there's no live view, the gap isn't found by the coordinator — it's found by a runner. The water station at mile four is empty and a runner texts a friend about it mid-race. The marshal never showed at the dangerous road crossing and someone improvises with a cone. By the time the coordinator hears about either, the race is already happening around the gap." },
      { type: 'list', items: [
        'A water station discovered empty by thirsty runners at mile four, not by anyone with the authority to fix it.',
        'A marshal no-show at an unguarded road crossing, found out only because someone posted about it afterward.',
        'Three volunteers who each thought they were covering the same aid station, and none covering the next one.',
        'Nobody sure who has the radio, the cones, or the extra water — because "who has what" lived in a text thread, not a list.',
      ] },
      { type: 'h2', text: 'What race morning looks like with one live roster' },
      { type: 'p', text: "The fix isn't a better spreadsheet sent out earlier — spreadsheets go stale the moment someone's plans change. It's a roster volunteers check into at their actual post, live, the same way runners check in at a finish line: idempotent QR scans that update one shared view instead of one more text nobody's sure landed. A coordinator watching that view on race morning sees exactly which of the nine posts are covered right now, and can redeploy a floating volunteer to a gap before a runner ever reaches it." },
      { type: 'quote', text: "A spreadsheet planned on Tuesday says nothing about who's actually standing at mile four on Saturday." },
      { type: 'p', text: "That's the actual job on race morning: not planning coverage, which the club already did weeks ago, but knowing in real time whether the plan held." },
    ],
    cta: { label: 'See the QR check-in mission control in the demo →', href: '/demo' },
  },
  {
    slug: 'winter-attrition-running-clubs',
    title: 'Winter attrition: why club attendance quietly halves every January',
    dek: "Eighty-five runners at the October Tuesday run. Forty by late January. Nobody decided that — it happened five percent at a time, and nobody was tracking the five percent.",
    category: 'Growth',
    readMinutes: 5,
    publishedAt: '2026-01-22',
    body: [
      { type: 'p', text: "A Tuesday night run that had eighty-five people on it in October has forty by the last week of January. No single event caused it — no bad run, no falling-out, no announcement. It happened in increments of two or three fewer people each week, small enough that nobody flagged any one Tuesday as the problem, until the cumulative number was impossible to ignore." },
      { type: 'h2', text: "The drop is gradual until it isn't" },
      { type: 'p', text: "The seasonal reasons are real and unsurprising: it's dark at 6 p.m., it's cold, and the habit that held together from March through the holidays takes a two-week break and doesn't automatically restart. But the reason the drop feels sudden in February is that almost no club is tracking week-over-week attendance closely enough to see it coming — a spreadsheet updated occasionally, or no record at all beyond someone's general sense of 'it felt quieter tonight.'" },
      { type: 'h2', text: "The members who don't come back never announce it" },
      { type: 'p', text: "Nobody cancels their club membership over text. They just stop showing up — first one Tuesday, then two, then it's been eight weeks and nobody noticed because there was never a moment that looked like a decision. The only real signal is attendance history, and if that history isn't being tracked in a way anyone actually looks at, the club finds out the same way it finds out about anything it isn't measuring: too late to do much about it." },
      { type: 'list', items: [
        'A member who ran three times a week for eight straight weeks in the fall, then zero times in the six weeks after New Year\'s, with no message either way.',
        'A weekly headcount that drops from 85 to 78 to 74 to 68 — each week a small enough dip that no single Tuesday triggers a conversation.',
        'An organizer\'s only signal being that Strava kudos and comments from a member have quietly dried up.',
        'A "we\'ll catch up in spring" assumption that\'s true for some members and false for others, with no way to tell which is which until spring arrives.',
      ] },
      { type: 'h2', text: 'Catching drift while it\'s still one missed week, not eight' },
      { type: 'p', text: "The alternative isn't guilt-tripping members back — it's catching the pattern in week two instead of week eight, when a personal 'haven't seen you, everything okay?' message still has a real chance of working, before the gap has calcified into a habit of its own. That requires attendance history a club can actually see trends in, and ideally a system flagging the drift automatically instead of relying on an organizer's memory of who used to show up." },
      { type: 'quote', text: "By the time a decline is visible on the whiteboard headcount, it isn't a trend anymore — it already happened." },
      { type: 'p', text: "This is exactly the kind of pattern-in-the-data problem a club running on scattered spreadsheets can't catch and a club with real attendance history can." },
    ],
    cta: { label: 'Talk to us about a founding-club pilot →', href: '/talk-to-us' },
  },
  {
    slug: 'club-constitution-playbook',
    title: 'Writing a club constitution nobody actually has to read to follow',
    dek: "Most club constitutions are a Google Doc written once at founding, never opened again, and quietly wrong about half of what the club actually does now.",
    category: 'Playbook',
    readMinutes: 5,
    publishedAt: '2026-01-29',
    body: [
      { type: 'p', text: "A club founded in 2019 has a Google Doc titled 'Club Constitution,' last edited three years ago. It lists a dues amount nobody currently charges, names two approved run leaders who moved away in 2022, and describes a cancellation policy that the current organizers have never once followed, because they didn't know it existed." },
      { type: 'h2', text: "A constitution nobody re-reads isn't governance, it's an artifact" },
      { type: 'p', text: "This is the normal state of a club document, not a failure of any particular club. Bylaws get written once, during the founding burst of energy when everything feels like it needs formalizing, and then nobody opens the document again until something goes wrong — a dues dispute, an injury on a group run, a founder stepping back — at which point it turns out the written policy and the lived practice diverged years ago and nobody updated either one." },
      { type: 'h2', text: 'The useful version is settings, not sentences' },
      { type: 'p', text: "Making the document longer or more thorough doesn't fix this — it just makes the drift more expensive to find later. The actual fix is moving the policies that matter out of prose and into the system members interact with every week, so the policy and the practice are the same thing by construction. Dues aren't a paragraph, they're an amount that actually charges. Run leaders aren't a name list from 2022, they're a role assigned in the system to whoever is currently doing the job." },
      { type: 'list', items: [
        'Dues amount and who\'s exempt — as an actual billing setting, not a sentence describing what dues "should" be.',
        'Who\'s an approved run leader right now — a role assigned in the system, not a name list nobody\'s updated since the person moved away.',
        'The weather cancellation threshold and who\'s authorized to call it — so it\'s a real notification trigger, not a judgment call reinvented every storm.',
        'What happens to a member\'s access if dues lapse — an automatic, consistent rule instead of an awkward one-off conversation.',
      ] },
      { type: 'h2', text: 'Succession is a settings problem too' },
      { type: 'p', text: "The scenario a written constitution is supposedly there for — the founder stepping back — is exactly where a document fails hardest, because whoever takes over has to first figure out what's still true. Admin roles that live in the system transfer cleanly: the new organizer can see, immediately, who's a run leader, what dues are set at, and what the actual cancellation policy is, because those are live settings rather than someone's memory of a Google Doc." },
      { type: 'quote', text: "The best club constitution is the one members never have to open, because the system already enforces it." },
      { type: 'p', text: "That's a five-step setup, not a rewrite project — the settings that matter get defined once, at onboarding, and then they're just how the club runs." },
    ],
    cta: { label: 'Start the onboarding wizard →', href: '/start' },
  },
  {
    slug: 'sponsorship-pitch-small-club',
    title: 'The sponsorship pitch a 40-member club can actually send',
    dek: "Most sponsorship advice assumes a club with thousands of members and a marketing team. A 40-person club has a real, sponsor-relevant asset too — it just has no data to prove it.",
    category: 'Growth',
    readMinutes: 4,
    publishedAt: '2026-02-05',
    body: [
      { type: 'p', text: "A 40-member club wants to pitch the local running shoe store for a modest sponsorship — some gear, a discount code, maybe fifty dollars toward post-run coffee. The organizer searches \"how to pitch a running sponsor,\" and every result assumes a club with five thousand Instagram followers, a media kit template, and someone whose actual job is partnerships. None of it applies, so the pitch never gets sent." },
      { type: 'h2', text: 'Forty members is a real audience, not a small one' },
      { type: 'p', text: "For a national brand, forty people is nothing. For a local running shoe store, physio, or coffee shop whose entire customer base lives within a few miles, forty engaged, hyper-local, weekly-recurring people is a genuinely valuable audience — arguably more valuable per person than a big vague following, because every one of them might actually walk into the store this month. The problem was never that the audience is too small. It's that the club has no way to prove it's real." },
      { type: 'h2', text: 'The credibility problem is a data problem' },
      { type: 'p', text: "'Our members shop local' is not a claim a sponsor can act on. 'Thirty-two of our forty members attended a run in the last four weeks, and the average member has run with us six times this quarter' is a different kind of claim — specific, verifiable, and exactly the sort of number a local business owner can weigh against the cost of a sponsorship. That number only exists if the club is actually tracking attendance and has real member data to draw from, with consent, rather than a guess." },
      { type: 'list', items: [
        'A branded mention at a weekly run with a real, current attendance number attached, not an estimate.',
        'Logo placement on an event page with a verifiable monthly view count, not a vague "we\'ll post about you."',
        'A discount code whose actual redemption rate the club can report back after the fact, not a one-time favor.',
        'A physical pop-up presence at a group run with a real RSVP count in hand before the sponsor even shows up.',
      ] },
      { type: 'quote', text: "A sponsor doesn't need five thousand followers — they need forty people who actually show up, and proof of it." },
      { type: 'p', text: "The pitch a small club can honestly send isn't a scaled-down version of a big club's media kit. It's a one-pager built entirely from real numbers the club already has, drafted in minutes instead of never, because the hard part was never the writing — it was not knowing which numbers to use." },
    ],
    cta: { label: 'Ask Pacer to draft a sponsor pitch in the demo →', href: '/demo' },
  },
  {
    slug: 'duty-of-care-running-clubs',
    title: 'Duty of care: what a volunteer-run club is actually responsible for',
    dek: "Duty of care isn't a scare tactic — it's whether an emergency contact, a guardian consent form, or a health flag can be found by whoever's on duty at 6am, not by whoever's holding the binder.",
    category: 'Privacy',
    readMinutes: 5,
    publishedAt: '2026-02-12',
    body: [
      { type: 'p', text: "It's 6:15am on a trail run when one of your members goes down hard on a root crossing — ankle bent at a wrong angle, not answering clearly. Someone kneels beside them while another runner jogs back to the cars for a phone with signal. Then comes the question nobody has a fast answer to: who do we call? The emergency contact is on a paper waiver signed at the club's very first event two years ago, sitting in a binder in an organizer's garage, unreachable at 6am on a Tuesday by anyone who actually needs it right now." },
      { type: 'h2', text: "Duty of care isn't a liability waiver you sign once" },
      { type: 'p', text: "Most volunteer organizers assume duty of care starts and ends with a signed waiver that protects the club from a lawsuit. In practice it's a more everyday obligation than that: keeping emergency contact information current and findable, knowing which members are minors in a youth program and who's authorized to collect them, and having some record of what happened if an incident does occur. None of this requires a lawyer on retainer. It requires the information existing somewhere findable, by whoever is present, in under a minute — not eventually, once someone gets home and checks a folder." },
      { type: 'h2', text: 'The paper folder nobody can find' },
      { type: 'p', text: "The gap almost never shows up during a calm Tuesday planning session — it shows up at the exact moment care is needed and nobody has a spare minute. A binder of signed waivers works fine until the volunteer who keeps it isn't at that day's run. A youth program's guardian consent forms work fine until a substitute coach is leading the session and has never seen the folder exists. The failure isn't negligence in the usual sense — it's that paper records live with a person, and the person holding them isn't always the one on duty." },
      { type: 'list', items: [
        'Emergency contact captured at registration and kept current — not a field filled in once, three seasons ago, and never revisited since.',
        "Guardian consent and pickup authorization on file for every minor in a youth program, visible to whichever coach actually runs that day's session.",
        'Any health flag a member has actively consented to share, visible to on-duty leads only — not buried in a paper intake form nobody re-reads.',
        "A timestamped record of any incident, so what actually happened isn't reconstructed from memory three days later when someone finally asks.",
      ] },
      { type: 'h2', text: 'What changes when the record is real, not paper' },
      { type: 'p', text: "Digitizing this isn't process for its own sake — it's making information findable by whoever is present, not whoever happens to be holding the binder that week. A member's emergency contact tied to their check-in record means anyone scanning people in at 6am can pull it up in seconds, regardless of who brought the folder. A consented health flag shows up to the lead on duty without anyone having to remember which intake form it was written on eighteen months ago. None of this is about scaring organizers into buying software — it's about closing a gap most clubs don't notice until the morning they need it closed." },
      { type: 'quote', text: 'A waiver nobody can find, at the moment it matters, is functionally the same as a waiver that was never signed.' },
    ],
    cta: { label: "Talk to us about your club's setup →", href: '/talk-to-us' },
  },
  {
    slug: 'injury-return-re-engagement',
    title: 'Bringing an injured member back without making it awkward',
    dek: "An injured runner doesn't want silence, and they don't want the group chat asking where they've been. What they need is a private, well-timed message from someone who actually noticed they were gone.",
    category: 'Product',
    readMinutes: 4,
    publishedAt: '2026-02-19',
    body: [
      { type: 'p', text: "An injured runner goes quiet for eight weeks. They don't post in the group chat, and they don't cancel anything, because there's nothing left on the calendar to cancel — they just stop showing up. By week three, nobody's really tracking it. By week eight, when they're finally cleared to run again, the club has two options, and both are wrong: say nothing and let them slide back into a Saturday run feeling like a stranger, or have someone ask 'hey, where have you been?' in front of the whole group chat, which is somehow worse." },
      { type: 'h2', text: 'Silence and the public callout are both the wrong instinct' },
      { type: 'p', text: "Silence reads as indifference, even when it isn't — the member assumes nobody noticed they were gone, which is a strange thing to come back to after eight weeks of physical therapy. The public version is worse: a well-meaning 'we missed you!' in a group thread of sixty people turns a private medical situation into a spectacle, and forces the member to either explain an injury to an audience or dodge the question in front of everyone. Neither option requires malice. Both come from the same root cause: nobody tracked why the person left in the first place." },
      { type: 'h2', text: 'The difference between going quiet from injury and just drifting away' },
      { type: 'p', text: "Generic churn and injury-driven absence look identical from the outside — both are a member who stops showing up. But the underlying signal is different if anyone's tracking it: a member who was RSVPing weekly and then abruptly stops, versus one who's been fading gradually for months, versus one who mentioned a sore knee at the last event they attended. Treating all three the same, with either silence or a generic broadcast, misses that the injured member usually wants back in — they just don't want to be the one who has to bring it up first." },
      { type: 'list', items: [
        "A private message, not a group post — sent to the one person, not broadcast to the sixty people who don't need to know.",
        "Timed to when it's actually useful — around the point a typical injury clears, not the week after they first went quiet.",
        "Specific, not generic — referencing the actual gap and the actual event they were last at, not a form-letter 'we miss you.'",
        "Distinct from a churn flag for someone who's just drifting — the message and the timing should differ because the situation does.",
      ] },
      { type: 'h2', text: "What this replaces isn't effort — it's guessing" },
      { type: 'p', text: "None of this requires an organizer to become a project manager tracking every member's physical therapy timeline. It requires the pattern — a sudden stop after regular attendance, no cancellations, a mention of an injury somewhere in event notes — to be visible somewhere other than one volunteer's memory. The nudge itself still has to sound like a person wrote it, not a bot. What changes is that someone gets prompted to write it at all, instead of the member's return depending on whether anyone happened to notice they were gone." },
      { type: 'quote', text: "The goal isn't to notice everyone who leaves. It's to notice the ones who left for a reason worth a private, well-timed word." },
    ],
    cta: { label: 'See churn flags in the live demo →', href: '/demo' },
  },
  {
    slug: 'waitlists-are-a-sales-channel',
    title: 'Waitlists are a sales channel, not a shrug',
    dek: "A sold-out workshop with eleven names on a waitlist isn't proof you're full — it's proof a second date would sell out too, sitting in an inbox until someone treats it like the sales signal it actually is.",
    category: 'Growth',
    readMinutes: 4,
    publishedAt: '2026-02-26',
    body: [
      { type: 'p', text: "A pottery workshop caps at 14 seats, sells out in four days, and eleven more people join a waitlist that lives in a Google Form nobody checks again after the event fills. The organizer's read on this is usually a shrug: 'guess we're full, sorry, catch the next one' — except there often isn't a next one, because nothing about a full waitlist gets treated as information. Eleven people who wanted in and didn't get a seat is the single strongest piece of demand data that workshop will generate, and it's about to sit in an inbox until everyone forgets about it." },
      { type: 'h2', text: "A shrug is a decision, even when it doesn't feel like one" },
      { type: 'p', text: "Treating a waitlist as an afterthought is itself a choice — it's choosing not to know whether a second session would sell out too. Eleven names on a list isn't 'unfortunate overflow,' it's a pre-validated audience for the next date: already interested, already aware of the workshop, already one email away from a yes. A sign-up sheet that ends at the door throws that list away the moment the workshop starts, right when it would be most valuable." },
      { type: 'p', text: "The reason waitlists rot in inboxes isn't laziness — it's that following up takes a manual email thread with each person, at a moment when the organizer is already deep in running the current session. By the time there's bandwidth to loop back, the interest has cooled and the list feels stale. The fix isn't asking organizers to be more diligent about email; it's making the follow-up something that happens on its own, tied to the event system that already knows who's on the list and what session comes next." },
      { type: 'h2', text: 'What a waitlist should actually trigger' },
      { type: 'p', text: "The useful version isn't complicated: waitlisted people get automatic first access when a second date opens, before the workshop is even announced publicly. And the decision to add that second date stops being a guess — it's backed by an actual number sitting in the system, not a vague sense that people seemed interested. A waitlist of three doesn't justify a second session. A waitlist of eleven, on a 14-seat room, is close to proof." },
      { type: 'list', items: [
        'First right of access for waitlisted members when a second date is added — before the general public sees it.',
        'A real number to make the call with: three waitlisted is a shrug, eleven on a 14-seat room is a second session waiting to happen.',
        "A follow-up that goes out automatically, not a manual reply an organizer means to send and doesn't get to for two weeks.",
        'A record of demand across sessions over time — which workshops consistently overflow, which ones just barely fill.',
      ] },
      { type: 'quote', text: "A full waitlist isn't a sign to apologize. It's a sign to schedule." },
    ],
    cta: { label: 'Create a workshop with a real waitlist →', href: '/new' },
    relatedWorkshopType: 'pottery',
  },
  {
    slug: 'pricing-a-workshop',
    title: 'Pricing a workshop: what the room actually costs you',
    dek: 'Most workshop hosts price the materials and forget the room, their own time, the no-shows, and the processing fees quietly eaten off every payment — which is how charging what feels fair turns into working for free.',
    category: 'Growth',
    readMinutes: 5,
    publishedAt: '2026-03-05',
    body: [
      { type: 'p', text: "A woodworking instructor prices a three-hour beginner class at $45 and, after materials — $18 in lumber and finish per seat — nets $27 a head before anything else gets subtracted. She hasn't yet counted the four hours she spent prepping and cleaning the shop, the $60 she pays to rent the space for the evening, the two no-shows she can expect out of ten registrations, or the roughly 3% that disappears to payment processing before the money even lands in her account. 'Charge what feels fair' is how most workshops get priced, and it's how most workshops end up quietly subsidized by the host's own unpaid time." },
      { type: 'h2', text: 'The cost stack nobody adds up' },
      { type: 'p', text: "Materials are the easy, visible cost — they're the thing an organizer can point to and say this cost me that much. Everything else is real money too, just less visible: the hours spent prepping and cleaning that never show up on a receipt, the venue or room rental whether it's a formal fee or an informal favor that eventually needs repaying, and the no-show rate that means a 10-seat class realistically has 8 paying attendees on the night, not 10. None of these show up on a materials list, so none of them make it into the price." },
      { type: 'h2', text: 'The two costs that vanish silently' },
      { type: 'p', text: "No-shows and processing fees both disappear without ever showing up as a line item. A workshop that plans for 10 full-price seats but reliably sees 2 no-shows is pricing as if it collects 100% of expected revenue when it's really collecting closer to 80% — unless the price accounts for that gap upfront. Payment processing eats another few percent on every transaction, silently, before the organizer ever sees the number. Neither of these is dramatic on its own. Stacked with underpriced time and an unaccounted venue cost, they're the difference between a workshop that pays for itself and one that pays the organizer in exposure." },
      { type: 'list', items: [
        'Materials, priced honestly per seat, not estimated once and never revisited as ingredient costs shift.',
        "Host time — prep, teaching, cleanup — valued at something above zero, even if it's below a full hourly rate.",
        'Room or venue cost, whether it is a hard rental fee or a favor that has a real value attached to it.',
        'A no-show buffer built into the price, so 10 registrations at 80% actual attendance still covers the room.',
      ] },
      { type: 'h2', text: 'What changes when the full stack is priced in' },
      { type: 'p', text: "Run the same three-hour class with the full stack counted — $18 in materials, a $15 allocation for host time, $6 for the room, a no-show buffer of roughly 20%, and about 3% lost to payment processing — and the price that actually covers the workshop is closer to $65 than $45. That's not overcharging; it's the difference between a number that was guessed and one that was calculated. Attendees rarely balk at $65 for three hours of real instruction — they balk at a class that mysteriously stops happening because it was never profitable to run in the first place." },
      { type: 'quote', text: 'What feels fair usually means what got forgotten — the room, the time, and the two people who never showed up.' },
    ],
    cta: { label: 'See the fee structure →', href: '/pricing' },
    relatedWorkshopType: 'woodworking',
  },
  {
    slug: 'workshop-or-course-series',
    title: 'One-off workshop or course series? The real tradeoff',
    dek: "A one-off that sold out and a four-week series that also sells out aren't the same product wearing a longer calendar — they carry different economics, different commitment, and a different way to break by week three.",
    category: 'Product',
    readMinutes: 4,
    publishedAt: '2026-03-12',
    body: [
      { type: 'p', text: "A one-off knife-sharpening workshop sells out, gets great feedback, and the natural next move feels obvious: turn it into a four-week series. Session one goes fine — it's basically a repeat of the workshop that worked. By week three, attendance has dropped from 16 to 9, half the no-shows never message to say why, and the organizer is running a class sized and priced for a one-off, four times, with less energy in the room each week. Nothing about the format changed on paper. Everything about what it demands changed in practice." },
      { type: 'h2', text: 'Two different products wearing the same name' },
      { type: 'p', text: "A one-off and a series aren't the same offering at different lengths — they're different products with different economics. A one-off sells a single ticket, once, and the organizer's job ends when the room empties. A series sells a commitment across four or six weeks, which means predictable revenue collected upfront, but also a much higher bar: attendees have to actually want to show up in week three, when the novelty has worn off and life gets in the way, not just once when a workshop looked interesting on Instagram." },
      { type: 'h2', text: 'Where the drop-off actually comes from' },
      { type: 'p', text: "Series attrition is rarely about the content getting worse — it's usually logistics compounding. A per-session ticket bought once at the excitement peak doesn't carry the same weight as a habit four weeks later, especially if nothing about the class communicates that this is a sequence, not four separate optional events. Bundled ticketing — pay once, commit to all four — versus per-session ticketing — pay each week, no penalty for skipping — produces genuinely different attendance patterns, and most organizers default into one without realizing it was a decision at all." },
      { type: 'list', items: [
        'Revenue: a series collects money upfront across weeks, better for planning; a one-off is faster to sell but tells you nothing about next month.',
        "Commitment: a series needs attendees who'll show up on the fourth Tuesday in a row, not just the first exciting one.",
        'Ticketing: bundled pricing, pay once for all sessions, drives attendance consistency; per-session pricing drives flexibility but invites drop-off.',
        "A series that's just the one-off repeated four times, with the same room size and no attrition plan, usually breaks by week three.",
      ] },
      { type: 'h2', text: 'What actually has to change, not just the calendar' },
      { type: 'p', text: "Turning a successful one-off into a series isn't a scheduling decision — it's a decision to redesign around a different failure mode. That might mean bundled pricing that makes the commitment explicit upfront, a slightly smaller room booked for realistic week-three attendance rather than week-one enthusiasm, or content that visibly builds from week to week so skipping one feels like a real loss, not a free pass. None of this is about picking the better format — a one-off and a series solve different problems, and the wrong choice for a given workshop just makes both harder." },
      { type: 'quote', text: 'A series is not a one-off repeated four times — it is a different bet on the same idea.' },
    ],
    cta: { label: 'Publish your first session free →', href: '/new' },
    relatedWorkshopType: 'woodworking',
  },
  {
    slug: 'materials-supply-costs',
    title: 'Materials and supply costs: the line item that quietly eats your margin',
    dek: "A studio orders clay for the headcount on a three-week-old sign-up sheet, not the one that actually shows up. That gap is where a workshop's margin quietly disappears.",
    category: 'Ops',
    readMinutes: 4,
    publishedAt: '2026-03-19',
    body: [
      { type: 'p', text: "A ceramics studio owner orders sixteen sets of clay and glaze because sixteen people signed up on a sheet three weeks ago. Eleven show up. Five kits go back in the cabinet, and the glaze that's already been mixed doesn't keep until next week. Nobody flags it as a loss — it's forty dollars, it happens most weeks, and it never shows up anywhere as a single number. It just quietly comes out of margin, session after session, until a year later the studio can't explain why materials cost almost double what the original pricing model assumed." },
      { type: 'h2', text: 'The sign-up sheet is a snapshot of the past, not the present' },
      { type: 'p', text: "Most workshop organizers order supplies off whatever registration count they had when they placed the order — often days before the session, because that's when there's time to shop. But registrations keep moving after that point: people cancel, no-show, or register late and never make it onto the version of the list the buyer actually looked at. A cooking class ordering proteins per head has the same problem in a more expensive, less forgiving form, because unlike clay, wasted chicken thighs can't be reused next week." },
      { type: 'h2', text: 'What a live headcount actually changes' },
      { type: 'p', text: "The fix isn't better spreadsheet discipline — it's moving the ordering decision closer to the event and basing it on a number that's actually current: confirmed registrations minus cancellations, as of the morning of the session, not the week it was announced. That one change turns materials ordering from a guess made too early into a decision made with nearly all the information that's ever going to be available." },
      { type: 'list', items: [
        'A live registration count means the person ordering supplies is working from the same number as the person running the door — not two spreadsheets updated on two different schedules.',
        'Cancellations and no-shows show up immediately, not as a surprise gap once the class has already started.',
        "Recurring sessions build a real no-show rate over time, so ordering can run on \"confirmed minus historical no-show %\" instead of \"confirmed plus hope.\"",
        'Waitlists fill seats that open up late, so materials bought for a full room actually get used by a full room.',
      ] },
      { type: 'quote', text: "Materials waste isn't a supply problem — it's a visibility problem wearing a supply costume." },
      { type: 'h2', text: 'Why the small version compounds into a real number' },
      { type: 'p', text: "A 20-30% overorder on materials, repeated weekly across a season, isn't a rounding error — it's thousands of dollars a year for a studio running even a modest schedule, and it's invisible precisely because it never arrives as one large bill. It's the gap between the margin a workshop was priced to deliver and the margin it actually delivers, and it closes as soon as ordering decisions run on a number that's true the morning of, not the week the sheet went up." },
    ],
    cta: { label: 'See where platform fees actually apply →', href: '/pricing' },
    relatedWorkshopType: 'pottery',
  },
  {
    slug: 'paying-instructors-without-spreadsheet',
    title: 'Paying instructors and hosts without a spreadsheet of IOUs',
    dek: "Flat fee, per-head split, cancelled session, under-filled class — multiply that by three instructors and one person's memory, and payday becomes a dispute waiting to happen.",
    category: 'Ops',
    readMinutes: 5,
    publishedAt: '2026-03-26',
    body: [
      { type: 'p', text: "A studio with three instructors running six sessions a week ends up with three different payment arrangements, tracked in one person's head: the pottery teacher gets a flat $60 per session regardless of turnout, the yoga instructor gets $8 per head with a $40 floor, and the guest host who filled in twice last month is owed... something, nobody's fully sure. At the end of the month someone opens a spreadsheet, reconstructs six weeks of sessions from memory and a calendar, and Venmos three people slightly different amounts than they expected. Nobody's stealing from anyone — it's just slow, informal, and it produces a dispute about once a quarter." },
      { type: 'h2', text: "The math isn't hard. Tracking it accurately, every week, is." },
      { type: 'p', text: "Per-session flat fees are simple until a session gets cancelled for weather or under-fills below the number that made it worth running — does the instructor still get paid, get a reduced rate, or get nothing? Per-attendee splits are simple until someone has to remember exactly how many people were actually in the room six weeks ago, as opposed to how many registered. None of this is complicated in isolation. It's complicated because attendance data lives in one place and payment records live in another, reconciled by hand, once a month, by whoever has the patience for it." },
      { type: 'h2', text: "What \"I'll Venmo you at the end of the month\" actually costs" },
      { type: 'p', text: "The dollar amounts in these disputes are usually small — twenty, forty dollars. What's expensive is what happens around them: an instructor who doesn't trust the math stops picking up extra sessions, starts asking for a running total, or quietly starts looking at a studio that pays automatically and on time. Informal payment isn't cheaper than a real system — it's just cheaper to set up, and the cost shows up later as instructor churn instead of as a line item on anyone's books." },
      { type: 'list', items: [
        'Payout per session calculates automatically from actual attendance, not a memory of how the room looked.',
        'Instructors can check their own running total in real time instead of asking for an update.',
        'Cancelled or under-filled sessions apply whatever rule was agreed on — reduced rate, flat minimum, nothing — the same way every time, not as a judgment call.',
        'A payout history exists as a record, so a dispute is a five-second lookup instead of a reconstruction from memory.',
      ] },
      { type: 'quote', text: "The instructor doesn't need to be paid more. They need to be able to check." },
      { type: 'h2', text: 'Where this stops being optional' },
      { type: 'p', text: "One instructor and one organizer can run on trust and a shared calendar indefinitely. The moment a studio has multiple people teaching, hosting, or subbing in — and multiple pay structures to match — trust stops being a system, and the reconciliation work grows faster than the schedule does. That's usually the point where a manual spreadsheet quietly becomes the biggest source of friction between an organizer and the people actually running their sessions." },
    ],
    cta: { label: 'Talk to us about multi-instructor payouts →', href: '/talk-to-us' },
    relatedWorkshopType: 'pottery',
  },
  {
    slug: 'workshop-alumni-retention',
    title: 'The alumni problem: why your best students never come back',
    dek: "The twelve people most likely to buy your next class are the twelve who just finished this one. Most organizers have no way to actually reach them.",
    category: 'Growth',
    readMinutes: 5,
    publishedAt: '2026-04-02',
    body: [
      { type: 'p', text: "Fourteen people finish a six-week wheel-throwing class. Twelve of them loved it and would sign up for an intermediate class in a heartbeat — if anyone told them it existed. Three months later, the studio posts \"Intermediate Wheel Throwing\" on Instagram as a general announcement, and maybe two of the original twelve ever see it, because Instagram doesn't show posts to everyone who follows an account and nobody thought to email the class list directly. The studio spends real money acquiring new beginners for the next intro class instead, because the twelve best prospects it already had were simply unreachable." },
      { type: 'h2', text: 'The alumni list that exists only as scattered threads' },
      { type: 'p', text: "Most workshop organizers have no single place where \"everyone who finished Beginner Ceramics in March\" lives as a list they can message. It's split across old email threads, a sign-up sheet from that specific session, and whatever's left in someone's memory. That's not a minor inconvenience — it means the people most likely to buy the next thing the studio sells are functionally unreachable, while the studio pays Eventbrite fees and ad spend chasing strangers who are less likely to convert than the alumni who already know and trust the place." },
      { type: 'h2', text: 'What changes when past attendees are a list, not a memory' },
      { type: 'p', text: "Treating alumni as an addressable segment means every person who finishes a session is automatically tagged with what they took and when, so \"everyone who completed Beginner Ceramics\" is a filter, not a research project. When the intermediate class opens, that list gets a direct message before the general public ever sees an announcement — and because they already know the studio, they convert at a rate a cold Instagram post never will." },
      { type: 'list', items: [
        "Every completed session automatically becomes a tag on that member's record — no manual list-building after the fact.",
        'Follow-up classes can be announced to exactly the people who finished the prerequisite, before the general public sees anything.',
        "A member who hasn't returned in three months shows up as a signal, not a mystery — a natural cue to reach out before they're gone for good.",
        'Revenue from the next session becomes more predictable, because a chunk of it is coming from people who already said yes once.',
      ] },
      { type: 'quote', text: 'A workshop that ends is not a customer relationship that ends — unless nobody kept the list.' },
      { type: 'p', text: "The honest tradeoff is that this only works if attendance and class history are captured in the first place, session after session, not reconstructed later from memory. But that's a one-time discipline, not an ongoing cost — and it's the difference between a workshop business that starts every month from zero and one that's quietly compounding a list of people who've already bought once." },
    ],
    cta: { label: 'See the growth automations in the demo →', href: '/demo' },
    relatedWorkshopType: 'pottery',
  },
  {
    slug: 'seasonal-capacity-planning',
    title: 'Seasonal capacity planning for a one-room studio',
    dek: "Twelve seats is twelve seats in January and in July. The demand hitting those seats isn't — and planning session by session guarantees you'll get both months wrong.",
    category: 'Playbook',
    readMinutes: 5,
    publishedAt: '2026-04-09',
    body: [
      { type: 'p', text: "A one-room studio has twelve seats, full stop — no amount of enthusiasm changes that number. In January, forty people try to book six seats. In July, six people book a session with room for twelve. Most organizers respond to each of these weeks as it comes: scrambling to fit resolution-season demand into a calendar posted a week or two out, then wondering in July why the room is half empty and quietly considering running fewer sessions. Both problems have the same root cause — planning session by session instead of planning the season." },
      { type: 'h2', text: 'Why week-to-week planning guarantees both problems' },
      { type: 'p', text: "If sessions get posted a week or two before they run, January demand shows up as a wave of people who can't get in, simply because there aren't enough sessions on the calendar yet to absorb it. Meanwhile the studio has no way to know six months out that July needs fewer sessions and lighter programming — a single evening drop-in instead of a full weekend workshop. Reacting to demand after it appears means always being one step behind a pattern that, for most workshop spaces, repeats every year almost exactly." },
      { type: 'h2', text: 'Planning around known capacity and a known curve' },
      { type: 'p', text: "The fix is treating a room's fixed seat count and the shape of seasonal demand as the two constants a season is built around, then filling the calendar to match — more sessions and earlier booking windows heading into the known high-demand months, fewer sessions or different formats heading into the known slow ones. This turns a calendar into a plan instead of a running list of reactions." },
      { type: 'list', items: [
        "Map last year's attendance by month first — the seasonal curve is usually more consistent than organizers expect.",
        "Open registration for the whole season at once instead of a week at a time, so demand has somewhere to go before it turns into a \"sorry, we're full\" message.",
        'Add sessions in the two or three months that reliably overbook, rather than discovering the overbook in real time.',
        'Use slow months for lower-commitment formats — single sessions, gift cards, drop-ins — instead of running the same six-week course to a half-empty room.',
      ] },
      { type: 'quote', text: "A full calendar in January and an empty one in July aren't two different problems. They're the same planning gap, twice." },
      { type: 'p', text: "None of this requires guessing further into the future than the data already supports — most one-room studios have at least a year of attendance history sitting in old registrations, and that history is usually a better predictor of next January than instinct is." },
    ],
    cta: { label: 'Plan your first season in the wizard →', href: '/start' },
  },
  {
    slug: 'weekly-active-members-metric',
    title: 'Weekly Active Members: the one number that tells you if a community is alive',
    dek: 'Total members only ever goes up. That\'s exactly why it\'s the wrong number to trust when a community is quietly losing the people who actually show up.',
    category: 'Product',
    readMinutes: 5,
    publishedAt: '2026-04-16',
    body: [
      { type: 'p', text: "A community's member count says 400 and climbing. Its actual weekly turnout has quietly dropped from ninety people to thirty over the past four months. Both of these things are true at the same time, and the first number is the one every organizer checks, because it's the one that only ever goes up — which is exactly why it's the wrong number to trust." },
      { type: 'h2', text: "Total members is a number that can't tell you bad news" },
      { type: 'p', text: "Membership counts accumulate. Someone who joined two years ago and hasn't shown up since counts exactly the same as someone who was at every session this month. A community can be actively dying — losing engagement, losing the sessions that made it worth joining — while its headline number keeps climbing on the strength of people who signed up once and never came back. By the time total members finally stalls, the decline has usually been happening for months already, unseen." },
      { type: 'h2', text: 'What Weekly Active Members catches instead' },
      { type: 'p', text: "Software companies stopped trusting total sign-ups for exactly this reason and started tracking weekly active users — the number of people who actually did something in the last seven days. The same shift applies directly to a running club, a gym, or a workshop studio: Weekly Active Members counts people who checked in, registered, or engaged in the last week, and it moves in both directions. A WACM number that's falling while total members keeps rising is the earliest, clearest signal that a community's core is thinning out — visible months before it shows up as empty sessions or a wave of cancelled memberships." },
      { type: 'list', items: [
        "Total members only ever goes up (or stays flat), so it can't signal decline until something drastic happens.",
        'WACM falls the same week engagement actually falls, not months later.',
        'A rising total-member count paired with a falling WACM is the single clearest early-warning pattern a community operator can track.',
        'WACM segments cleanly by cohort — which class, which join month — showing exactly where retention is breaking.',
      ] },
      { type: 'quote', text: 'Total members tells you how many people once said yes. Weekly Active Members tells you how many still mean it.' },
      { type: 'p', text: "None of this requires new data — check-ins, RSVPs, and session attendance already exist somewhere in most organizers' tools. The only change is looking at a rolling seven-day window instead of a lifetime total, and treating a drop in that window as the early warning it actually is, instead of noise." },
    ],
    cta: { label: 'See WACM tracked live in the demo →', href: '/demo' },
  },
  {
    slug: 'volunteer-burnout-warning-signs',
    title: 'Volunteer burnout: the warning signs, three weeks before it happens',
    dek: 'Response times slip. Events get published later. The messages get shorter. By the time anyone notices, the person holding the club together has already checked out.',
    category: 'Ops',
    readMinutes: 4,
    publishedAt: '2026-04-20',
    body: [
      { type: 'p', text: "Three weeks before a volunteer organizer quietly stops replying, the warning signs are already sitting in the group chat — you just have to know what you're looking at. The RSVP that used to get an answer within the hour now sits for two days. The event that always went live on Monday goes live Wednesday, then the following Thursday. Nobody flags it, because each individual delay looks like a busy week, not a pattern building toward someone stepping back for good." },
      { type: 'h2', text: 'The organizer is the API' },
      { type: 'p', text: "In most communities that haven't moved off spreadsheets and group chats, one person is doing the work seven different tools should be doing for each other. Every RSVP from Eventbrite gets copied into a Google Sheet by hand. Every payment from PayPal gets matched to a name from memory. Every reminder gets typed into WhatsApp because there's no automated one. That person isn't running the club — they're manually routing data between apps that don't talk to each other, and the club is running on their attention." },
      { type: 'h2', text: 'What actually shows up three weeks out' },
      { type: 'list', items: [
        'Response time creeps from hours to days — not because the organizer stopped caring, but because every reply now competes with the copying-and-pasting nobody else sees.',
        'Events get published later in the week, then later in the day, as the pre-event checklist gets squeezed into a smaller window each time.',
        'Messages get shorter and flatter — the enthusiastic paragraph becomes a one-line "same time, same place."',
        'Small extras quietly disappear first: the welcome message to a new member, the recap photos, the shoutout to whoever showed up for the fifth week straight.',
      ] },
      { type: 'h2', text: "Self-care advice doesn't fix a broken pipeline" },
      { type: 'p', text: "The standard advice — delegate more, take a week off, set boundaries — treats the workload as something to manage rather than a system to fix. But you can't delegate a task that only exists because two tools don't sync, and a week off just means the RSVPs pile up unanswered until the organizer gets back to them. Someone else stepping in doesn't help either, because the knowledge of how the seven tools fit together usually lives in one person's head, not in any document a replacement could read." },
      { type: 'p', text: "The fix that actually holds is removing the manual routing itself: one place where RSVPs, payments, and reminders already talk to each other, so the organizer's job goes back to being organizing instead of copying. That's not a smaller version of the same job — it's a different job, and it's the one that doesn't quietly burn someone out every few months." },
      { type: 'quote', text: "Burnout isn't a personality problem — it's a queueing problem with a human stuck in the queue." },
    ],
    cta: { label: 'Talk to us about white-glove migration →', href: '/talk-to-us' },
  },
  {
    slug: 'free-tier-paid-tier-line',
    title: 'Free tier, paid tier: where to actually draw the line',
    dek: "Members built your culture for free. Charge the wrong thing and you turn them into customers of the community they founded — here's the line that actually holds.",
    category: 'Growth',
    readMinutes: 4,
    publishedAt: '2026-04-23',
    body: [
      { type: 'p', text: "A running club with 400 members proposes a supporter tier — early access to race registrations, a branded jacket, a shoutout in the newsletter — and within an hour someone in the group chat asks the only question that matters: 'Wait, do I have to pay now?' That single message is the entire monetization problem in eight words. Get the free/paid line wrong and you don't just lose revenue, you signal to the people who built the culture that they're suddenly guests in it." },
      { type: 'h2', text: 'What has to stay free, always' },
      { type: 'p', text: "The core gathering — the event itself, the RSVP, the ability to show up and be counted as a member — is what the community was built on, usually by people who paid nothing and gave their time instead. Charging for basic participation doesn't just alienate them, it rewrites the deal retroactively. Whatever else changes, the thing that made someone a member in the first place has to stay exactly as free as it was the day they joined." },
      { type: 'p', text: "This matters most in the first year of any monetization push, when the loudest members are also the ones who showed up before there was anything to show up to. Ask them to start paying for what they already have and the message they hear isn't 'we're growing' — it's 'you were a beta tester, and beta testers don't get equity.'" },
      { type: 'h2', text: "What's fair to gate" },
      { type: 'list', items: [
        'Priority or early registration for popular events, rather than access to the event itself.',
        "A genuinely premium tier of programming — a weekend retreat, a workshop with an outside instructor, a small-group session — that's additive, not a fenced-off version of what used to be free.",
        'Recognition and perks that cost the organizer real money to provide: a jacket, a pin, a name on a supporter wall.',
        'Sponsor-facing benefits, like a logo placement or a booth, which sponsors expect to pay for regardless.',
        'Administrative conveniences — faster check-in, a dedicated support channel — that save time without gating belonging.',
      ] },
      { type: 'h2', text: 'One honest example, not the only answer' },
      { type: 'p', text: "RunOS draws this line by charging the organization, not the member — members never see a paywall to join or RSVP, and the platform fee the club pays on transactions shrinks as it grows, from 2% down to 1% and then 0.5%. That's one defensible place to draw the line: Starter is free under 50 members, Club is $79 a month, Pro is $199, and Network pricing starts at $999 for the largest multi-chapter organizations. It works because the free tier isn't a stripped-down trial — it's the actual product, for as long as the club stays small." },
      { type: 'quote', text: "The people who paid nothing to build your culture shouldn't have to pay to keep participating in it." },
    ],
    cta: { label: 'See how the tiers are actually structured →', href: '/pricing' },
  },
  {
    slug: 'hybrid-events-what-first',
    title: 'Hybrid events: what to build first when half your community is remote',
    dek: "Half your members are in the room; half are three time zones away. The fix isn't a $400 camera — it's a page that stops assuming everyone's local.",
    category: 'Product',
    readMinutes: 5,
    publishedAt: '2026-04-27',
    body: [
      { type: 'p', text: "A monthly book club with 60 members — 40 local, 20 scattered across three time zones — decides it's time to 'do hybrid,' and the organizer's first move is pricing out a $400 camera and a tripod mount. Six weeks later the livestream is live, crisp, and watched by exactly two people, because the actual problem was never video quality. It was that the event page said '7pm at Riverside Café' with no indication anyone remote was expected, wanted, or welcome." },
      { type: 'h2', text: "The expensive thing isn't the broken thing" },
      { type: 'p', text: 'Hybrid gets treated as an AV problem because AV is the visible, purchasable part. But most hybrid communities fail earlier than that — at the event page, the RSVP form, and the reminder email — all of which assume, by default wording alone, that everyone attending is walking through a physical door. Fixing the camera before fixing that assumption is polishing a page nobody remote believed was meant for them in the first place.' },
      { type: 'p', text: "A remote member who has to guess whether they're actually invited, or dig through a Calendly link to figure out what time an event starts in their own zone, will simply stop RSVPing before they ever get to judge the stream quality. By the time the camera matters, the page has already lost most of the audience it was bought for." },
      { type: 'h2', text: 'Fix the page before the pixels' },
      { type: 'list', items: [
        'One event page, not two — a separate "virtual" listing splits the community into a real event and an afterthought before anyone even RSVPs.',
        'An RSVP that asks "in person or remote" as a normal option, not a special case bolted on afterward.',
        'Reminders that say "see you Thursday" instead of "see you at Riverside Café" to someone joining from another country.',
        "Times that convert automatically for the reader's own time zone instead of listing one time and leaving the math to them.",
        'A join link placed exactly where the address goes — same visual weight, same level of "this is expected."',
      ] },
      { type: 'h2', text: 'What actually deserves investment, in order' },
      { type: 'p', text: "Once the page, RSVP, and reminders treat remote attendance as a first-class option instead of an exception, the next fix is usually a $50 phone tripod and a clip-on microphone — good enough for a remote member to follow along and feel present. Dedicated cameras, switchers, and a real AV budget are a reasonable investment eventually, but only after the cheap fixes prove people actually show up remotely once the basics stop excluding them. Spend on production quality before that point and you're polishing a stream for an audience the RSVP form never let in." },
      { type: 'quote', text: 'Hybrid fails at the RSVP form long before it ever fails at the camera.' },
    ],
    cta: { label: 'Publish an event either way — free, 60 seconds →', href: '/new' },
  },
  {
    slug: 'founding-member-cohort',
    title: 'The founding-member cohort: why the first 20 people decide the next 2,000',
    dek: "Nobody votes on a community's culture. The first 20 people who show up just build it — on purpose or by accident.",
    category: 'Playbook',
    readMinutes: 5,
    publishedAt: '2026-04-30',
    body: [
      { type: 'p', text: "The first 20 people who show up to a new community don't just fill seats — they decide, mostly without meaning to, who future members are joining. The inside jokes, who talks first at an event, whether a newcomer gets introduced around or left standing near the snacks: none of that gets written down anywhere, and all of it gets set in the first few months by whoever happened to be in the room." },
      { type: 'h2', text: 'Culture is set before the growth chart bends' },
      { type: 'p', text: "By the time a community has 2,000 members, its founding norms are effectively load-bearing — new members absorb them by watching, not by being told. If the founding cohort skewed toward one clique, one experience level, or one personality type, that's the default new people get measured against, whether or not it was ever the intention. Fixing culture at 2,000 members is a much bigger project than shaping it at 20." },
      { type: 'p', text: "This is why two communities can start with an identical mission statement and end up feeling completely different a year later. The mission never decided who felt at home — the first 20 people did, in a hundred small interactions nobody was tracking at the time." },
      { type: 'h2', text: 'Invite deliberately, not widely' },
      { type: 'list', items: [
        "Personally invite the first 15-20 people rather than posting one wide call — you're choosing who sets the tone, not just who fills the room.",
        'Keep the first few events small enough that everyone actually talks to everyone, not just to whoever they arrived with.',
        'Assign someone — even informally — to greet and introduce newcomers at every early event, before "who welcomes people" becomes an unwritten job nobody does.',
        'Write down the norms as soon as you notice them forming, so they can be taught on purpose instead of absorbed by osmosis.',
        'Hold off on the wide Instagram push or public listing until the small group feels like the community you actually want, not just a batch of early joiners.',
      ] },
      { type: 'h2', text: 'Resist the urge to blast wide too soon' },
      { type: 'p', text: 'The instinct to grow fast is strong, especially once the first event goes well — but broadcasting to a few thousand followers before the founding cohort has settled its norms just means the next 200 people set the culture instead of the twenty you chose. A slower, deliberate open is the harder call in the moment and the easier one two years later, because it means growth adds to a culture that already exists instead of deciding one by default.' },
      { type: 'quote', text: "The first 20 people don't just join your community — they write its constitution, whether you ask them to or not." },
    ],
    cta: { label: 'Talk to us about the founding-club program →', href: '/talk-to-us' },
  },
  {
    slug: 'post-event-feedback-loop',
    title: "Post-event feedback that isn't a survey nobody opens",
    dek: "A Google Form emailed the next morning gets a 5% response rate and a lot of silence. The fix isn't a better survey — it's a smaller, faster, better-timed question.",
    category: 'Product',
    readMinutes: 4,
    publishedAt: '2026-05-01',
    body: [
      { type: 'p', text: "A workshop organizer emails a Google Form survey the morning after every session — twelve questions, a five-point scale, a text box at the end. Response rate: about one in twenty. Of those, half are one-word answers and one is someone venting about parking. Six months of this and the organizer still doesn't know whether the new format is actually working, because the form arrives late, asks too much, and leads nowhere anyone can see." },
      { type: 'h2', text: 'The form arrives too late and asks too much' },
      { type: 'p', text: "A next-morning survey is competing with everything else in someone's inbox on a day they've already mentally moved past the event. Twelve questions is a chore, not a favor, and a five-point scale on 'overall satisfaction' rarely tells an organizer anything they can act on by next week. The response rate isn't a mystery — it's a rational reaction to a form that costs more than it's worth to the person filling it out." },
      { type: 'p', text: "And even a perfect response rate wouldn't fix the deeper issue: a generic satisfaction score doesn't tell an organizer which specific decision to make next. 'It was fine' is a real answer nineteen times out of twenty, and it's useless." },
      { type: 'h2', text: 'What a lighter loop looks like' },
      { type: 'list', items: [
        'One specific question, not twelve general ones — "was the new start time better or worse?" gets answered; "how did we do?" doesn\'t.',
        "Asked same-day, ideally at the door on the way out, while the event is still the thing on someone's mind.",
        'A single tap or a QR code, not a form with a login wall or ten required fields.',
        'A visible close of the loop — "you told us the room was too loud, so we moved it" — so the next ask doesn\'t feel like shouting into a void.',
      ] },
      { type: 'h2', text: 'Attendance is already feedback' },
      { type: 'p', text: "Long before anyone fills out a survey, the RSVP and check-in data has already said something: who came, who said yes and didn't show, who's been at every session for two months, and who quietly stopped after one. That pattern is feedback an organizer usually has and rarely looks at, because it's shaped like a spreadsheet instead of a survey response. It's also the exact signal RunOS's Pacer uses to flag a member drifting toward churn before they've said a word about why." },
      { type: 'quote', text: "Your attendance sheet has been telling you what's working for months — nobody read it because it wasn't shaped like a survey." },
    ],
    cta: { label: 'See attendance and feedback loops in the demo →', href: '/demo' },
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function otherArticles(slug: string, count = 2): Article[] {
  return ARTICLES.filter((a) => a.slug !== slug).slice(0, count);
}
